server:
  host: 0.0.0.0
  port: 8080
  base_path: /api

database:
  host: 193.112.175.178
  port: 15432
  user: xbmlz
  password: xbmlz@666
  name: go_web_template
  args: sslmode=disable TimeZone=Asia/Shanghai

token:
  secret: xxx
  expiration: 3600

log:
  level: debug
  filename: logs/app.log
  max_size: 500
  max_backups: 30
  max_age: 15
  compress: true
