basePath: /api/v1
definitions:
  dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  dto.RegisterResponse:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server for go-web-template
  title: go-web-template API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - description: 注册请求
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 注册响应
          schema:
            $ref: '#/definitions/dto.RegisterResponse'
      summary: 注册
      tags:
      - auth
swagger: "2.0"
